routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\WelcomeController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\OfferController;
use App\Http\Controllers\Account\IndexController;
use App\Http\Controllers\Admin\ParserController;
use App\Http\Controllers\Auth\SocialController;
use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\NewsController as AdminNewsController;
use App\Http\Controllers\Admin\IndexController as AdminIndexController;
use App\Http\Controllers\Admin\UserController as AdminUserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [WelcomeController::class, 'index'])
    ->name('welcome');

Route::get('/categories', [CategoryController::class, "index"])
    ->name('categories');

Route::get('/news/{category}', [NewsController::class, "index"])
    ->name('news')
    ->where(['category' => '\d+']);

Route::get('/news/{id}/{category}', [NewsController::class, "show"])
    ->name('news.show')
    ->where([
        'category' => '\d+',
        'id' => '\d+',
    ]);

Route::resource('offer', OfferController::class);

Route::get('/about', [AboutController::class, "index"])
    ->name('about');

Route::group(['middleware' => 'auth'], function() {
    Route::group(['prefix' => 'account', 'as' => 'account.'], function() {

        Route::get('/', IndexController::class)
            ->name('index');

        Route::get('/logout', function() {
            Auth::logout();
            return redirect()->route('login');
        })->name('logout');
    });

    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin.check'], function () {
        Route::get('/', AdminIndexController::class)
            ->name('index');

        Route::get('parser', ParserController::class)
            ->name('parser');

        Route::resource('categories', AdminCategoryController::class);
        Route::resource('news', AdminNewsController::class);
        Route::resource('users', AdminUserController::class);
    });
});

Auth::routes();

Route::group(['middleware' => 'guest'], function() {
    Route::get('auth/{social}/redirect', [SocialController::class, 'index'])
        ->where('social', '\w+')
        ->name('auth.redirect');

    Route::get('auth/{social}/callback', [SocialController::class, 'callback'])
        ->where('social', '\w+')
        ->name('auth.callback');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/OfferController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\View\View;

class OfferController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index(): View
    {
        return view('offer.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request): RedirectResponse
    {
        $data = json_encode($request->except('_token'));
        file_put_contents('userOffer.json', $data, FILE_APPEND);

        if(!$data) {
            return back()->with('error', 'Ошибка при добавлении категории');
        }

        return redirect()->route('offer.index')
            ->with('success', 'Данные отправлены! Мы скоро свяжемся с Вами');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/offer/index.blade.php
@extends('layouts/main')

@section('title') Предложение | @parent @endsection

@section('greeting')
    <x-main.greeting
        title="Предложите нам свою новость"
    />
@endsection

@section('content')
    <div class="container px-4 py-5 mt-5" id="featured-3">
        <h2>Предложите новость</h2>

        @include('inc.messages')

        <x-ui.form
            method="POST"
            route="{{ route('offer.store') }}"
            custom-method=""
            enctype=""
        >
            <x-ui.input
                name="userName"
                title="Имя"
                type="text"
                value=""
            />

            <br>

            <x-ui.input
                name="userPhone"
                title="Телефон"
                type="tel"
                value=""
            />

            <br>

            <x-ui.input
                name="userEmail"
                title="Почта"
                type="email"
                value=""
            />

            <br>

            <x-ui.textarea
                name="description"
                title="О чём бы вы хотели написать?"
            />

            <x-slot:button>
                <x-ui.button
                    type="submit"
                    cssClass="btn-outline-primary"
                >
                    Отправить
                </x-ui.button>
            </x-slot:button>
        </x-ui.form>
    </div>
@endsection