routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

use App\Http\Controllers\WelcomeController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\NewsController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\OfferController;
use App\Http\Controllers\Account\IndexController;
use App\Http\Controllers\Admin\ParserController;
use App\Http\Controllers\Auth\SocialController;
use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\NewsController as AdminNewsController;
use App\Http\Controllers\Admin\IndexController as AdminIndexController;
use App\Http\Controllers\Admin\UserController as AdminUserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [WelcomeController::class, 'index'])
    ->name('welcome');

Route::get('/categories', [CategoryController::class, "index"])
    ->name('categories');

Route::get('/news/{category}', [NewsController::class, "index"])
    ->name('news')
    ->where(['category' => '\d+']);

Route::get('/news/{id}/{category}', [NewsController::class, "show"])
    ->name('news.show')
    ->where([
        'category' => '\d+',
        'id' => '\d+',
    ]);

Route::resource('offer', OfferController::class);

Route::get('/about', [AboutController::class, "index"])
    ->name('about');

Route::group(['middleware' => 'auth'], function() {
    Route::group(['prefix' => 'account', 'as' => 'account.'], function() {

        Route::get('/', IndexController::class)
            ->name('index');

        Route::get('/logout', function() {
            Auth::logout();
            return redirect()->route('login');
        })->name('logout');
    });

    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin.check'], function () {
        Route::get('/', AdminIndexController::class)
            ->name('index');

        Route::get('parser', ParserController::class)
            ->name('parser');

        Route::resource('categories', AdminCategoryController::class);
        Route::resource('news', AdminNewsController::class);
        Route::resource('users', AdminUserController::class);
    });
});

Auth::routes();

Route::group(['middleware' => 'guest'], function() {
    Route::get('auth/{social}/redirect', [SocialController::class, 'index'])
        ->where('social', '\w+')
        ->name('auth.redirect');

    Route::get('auth/{social}/callback', [SocialController::class, 'callback'])
        ->where('social', '\w+')
        ->name('auth.callback');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Category extends Model
{
    use HasFactory;

    protected $table = 'Categories';

    protected $fillable = [
        'title',
        'is_active',
        'description',
    ];

    protected $casts = [
        'is_active' => 'boolean',
    ];

    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }

    public function news(): hasMany
    {
        return $this->hasMany(News::class, 'category_id', 'id');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;

use App\Http\Requests\Category\CreateRequest;
use App\Http\Requests\Category\EditRequest;
use App\Models\Category;

use Exception;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Log;
use Illuminate\View\View;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index(): View
    {
        return view('admin.categories.index', [
            'categoriesList' => Category::orderBy('id', 'desc')->withCount('news')->paginate(5),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create(): View
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateRequest $request
     * @return RedirectResponse
     */
    public function store(CreateRequest $request): RedirectResponse
    {
        $newCategory = Category::create($request->validated());

        if(!$newCategory) {
            return back()->with('error', __('messages.admin.categories.create.fail'));
        }

        return redirect()->route('admin.categories.index')
            ->with('success', __('messages.admin.categories.create.success'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Category $category
     * @return View
     */
    public function edit(Category $category): View
    {
        return view('admin.categories.edit', [
            'category' => $category
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param EditRequest $request
     * @param Category $category
     * @return RedirectResponse
     */
    public function update(EditRequest $request, Category $category): RedirectResponse
    {
        $status = $category->fill($request->validated())->save();

        if(!$status)
        {
            return back()->with('error', __('messages.admin.categories.update.fail'));
        }

        return redirect()->route('admin.categories.index')
            ->with('success', __('messages.admin.categories.update.success'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Category $category
     * @return JsonResponse
     */
    public function destroy(Category $category): JsonResponse
    {
        try {
            $category->delete();

            return response()->json(['status' => 'ok']);
        } catch(Exception $e) {
            Log::error("Category wasn't delete");

            return response()->json(['status' => 'error'], 400);
        }
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;

use Illuminate\Http\Request;
use Illuminate\View\View;

class CategoryController extends Controller
{
    public function index(): View
    {
        return view('categories.index', [
            'categoriesList' => Category::active()->orderBy('id', 'desc')->get(),
        ]);
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts/admin')

@section('title') Создать категорию | @parent @endsection

@section('menu')
    <x-admin.sidebar />
@endsection

@section('content')
    <div class="header">
        <h1>Создать категорию</h1>
    </div>

    <div class="content">
        <div>
            @include('inc.messages')

            <x-ui.form
                method="POST"
                route="{{ route('admin.categories.store') }}"
                custom-method=""
                enctype=""
            >
                <x-ui.input
                    name="title"
                    title="Наименование"
                    type="text"
                    value="{{ old('title') }}"
                />

                <x-ui.select
                    name="is_active"
                    title="Активировать?"
                >
                    <option
                        @if(old('is_active') === true) selected @endif
                        value="1"
                    >
                        Да
                    </option>

                    <option
                        @if(old('is_active') === false) selected @endif
                        value="0"
                    >
                        Нет
                    </option>
                </x-ui.select>

                <x-ui.textarea
                    name="description"
                    title="Описание"
                >
                    {{ old('description') }}
                </x-ui.textarea>

                <x-slot:button>
                    <x-ui.button
                        type="submit"
                        cssClass="btn-outline-primary"
                    >
                        Создать категорию
                    </x-ui.button>
                </x-slot:button>

            </x-ui.form>
        </div>
    </div>
@endsection

@push('js')
    <script src="https://cdn.ckeditor.com/ckeditor5/34.0.0/classic/ckeditor.js"></script>
    <script src="https://ckeditor.com/apps/ckfinder/3.5.0/ckfinder.js"></script>

    <script>

        ClassicEditor
            .create(document.querySelector('#description'), {
                toolbar: {
                    items: [
                        'heading', '|',
                        'bold', 'italic', 'strikethrough', 'underline', 'subscript', 'superscript', '|',
                        'link', '|',
                        'outdent', 'indent', '|',
                        'bulletedList', 'numberedList', 'todoList', '|',
                        'code', 'codeBlock', '|',
                        'insertTable', '|',
                        'ckfinder', 'blockQuote', '|',
                        'undo', 'redo'
                    ],
                    shouldNotGroupWhenFull: true
                },

                ckfinder: {
                    uploadUrl: 'https://example.com/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images&responseType=json',

                    options: {
                        resourceType: 'Images'
                    }
                }
            })
            .catch(error => {
                console.error(error);
            });
    </script>
@endpush

resources/views/admin/categories/edit.blade.php
@extends('layouts/admin')

@section('title') Редактировать категорию | @parent @endsection

@section('menu')
    <x-admin.sidebar />
@endsection

@section('content')
    <div class="header">
        <h1>Редактировать категорию</h1>
    </div>

    <div class="content">
        <div>
            @include('inc.messages')

            <x-ui.form
                method="POST"
                route="{{ route('admin.categories.update', ['category' => $category->id]) }}"
                custom-method="PUT"
                enctype=""
            >

                <x-ui.input
                    name="title"
                    title="Наименование"
                    type="text"
                    :value="$category->title"
                />

                <x-ui.select
                    name="is_active"
                    title="Активировать?"
                >
                    <option
                        @if($category->is_active === true) selected @endif
                        value="1"
                    >
                        Да
                    </option>

                    <option
                        @if($category->is_active === false) selected @endif
                        value="0"
                    >
                        Нет
                    </option>
                </x-ui.select>

                <x-ui.textarea
                    name="description"
                    title="Описание"
                >
                    {!! $category->description !!}
                </x-ui.textarea>

                <x-slot:button>
                    <x-ui.button
                        type="submit"
                        cssClass="btn-outline-primary"
                    >
                        Сохранить
                    </x-ui.button>
                </x-slot:button>
            </x-ui.form>

        </div>
    </div>
@endsection

@push('js')
    <script src="https://cdn.ckeditor.com/ckeditor5/34.0.0/classic/ckeditor.js"></script>
    <script src="https://ckeditor.com/apps/ckfinder/3.5.0/ckfinder.js"></script>

    <script>

        ClassicEditor
            .create(document.querySelector('#description'), {
                toolbar: {
                    items: [
                        'heading', '|',
                        'bold', 'italic', 'strikethrough', 'underline', 'subscript', 'superscript', '|',
                        'link', '|',
                        'outdent', 'indent', '|',
                        'bulletedList', 'numberedList', 'todoList', '|',
                        'code', 'codeBlock', '|',
                        'insertTable', '|',
                        'ckfinder', 'blockQuote', '|',
                        'undo', 'redo'
                    ],
                    shouldNotGroupWhenFull: true
                },

                ckfinder: {
                    uploadUrl: 'https://example.com/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images&responseType=json',

                    options: {
                        resourceType: 'Images'
                    }
                }
            })
            .catch(error => {
                console.error(error);
            });
    </script>
@endpush

resources/views/admin/categories/index.blade.php
@extends('layouts/admin')

@section('title') Список категорий | @parent @endsection

@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
        <h1 class="h2">Список категорий</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <a href="{{ route('admin.categories.create') }}" class="btn btn-sm btn-outline-secondary">
                    Добавить категорию
                </a>
            </div>
        </div>
    </div>

    <div class="content">
        <div class="table-responsive">
            @include('inc.messages')
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>#ID</th>
                    <th>Кол-во новостей</th>
                    <th>Заголовок</th>
                    <th>Описание</th>
                    <th>Активность</th>
                    <th>Опции</th>
                </tr>
                </thead>
                <tbody>
                @forelse($categoriesList as $category)
                    <tr>
                        <td>{{ $category->id }}</td>
                        <td>{{ $category->news_count }}</td>
                        <td>{{ $category->title }}</td>
                        <td>{{ $category->description }}</td>
                        <td>{{ $category->is_active ? 'активна' : 'неактивна' }}</td>
                        <td>
                            <a href="{{ route('admin.categories.edit', ['category' => $category->id]) }}">Ред.</a>
                            &nbsp;
                            <a href="javascript:;" class="delete" id="{{ $category->id }}" style="color:red;">Удл.</a>
                        </td>
                    </tr>
                @empty
                    <tr><td colspan="4">Записей нет</td></tr>
                @endforelse
                </tbody>
            </table>

            {{ $categoriesList->links() }}
        </div>
    </div>
@endsection

@push('js')
    <script>
        document.addEventListener("DOMContentLoaded", () => {

            const item = document.querySelectorAll(".delete");

            item.forEach(function (el, index) {
                el.addEventListener("click", function () {
                    const id = this.getAttribute("id");
                    if (confirm(`Подтвердите удаление категории с #ID ${id} ?`)) {
                        //send id on backend
                        send(`/admin/categories/${id}`).then(() => {
                            alert("Категория была удалена");
                            location.reload();
                        });
                    }
                });
            });
        });

        async function send(url) {
            let response = await fetch(url, {
                method: 'DELETE',
                headers: {
                    'Content-Type': 'application/json',
                    'Accept': 'application/json',
                    'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]')
                        .getAttribute('content')
                }
            });
            let result = await response.json();
            return result.ok;
        }

    </script>
@endpush